version: '3'
services:
  postgres:
    image: postgres:9.4-alpine
    ports:
      - '127.0.0.1:5432:5432'
  elasticsearch:
    image: hypothesis/elasticsearch:latest
    ports:
      - '127.0.0.1:9201:9200'
    environment:
      - discovery.type=single-node
  elasticsearchold:
    image: nickstenning/elasticsearch-icu
    ports:
      - '127.0.0.1:9200:9200'
  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
  web:
    image: signalio/travrse-h:latest
    ports:
      - '0.0.0.0:80:4999'
      - '0.0.0.0:443:5000'
    env_file:
      - /var/code/travrse-main/conf/prod-h.trvr.se.env
    volumes:
      - /var/code/travrse-main/conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/travr.se/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/travr.se/privkey.pem:/etc/nginx/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/nginx/ssl-dhparams.pem
      - /var/www/travrse-landing-page/homepage:/var/www/html
